### PR TITLE
Support for single vs multiple tags and fixed tags

### LINKED ISSUE #2: Support additional tags
Add support for «tagsadditional» on signup form. This should be a hidden field.

### PR DESCRIPTION
**Pull request by stianpr**
We now support creating a signup form that either has single (radio
inputs) or multiple (checkbox inputs) choices in the form. We also
support sending fixed tags with the subscription. Meaning that all
subscribers will receive this tag in MailMojo.

Resolves #2

### CODE REVIEW

**Comment by asteinlein** [comment]
Seems like this includes more changes than relevant to this particular patch?

**Comment by stianpr** [comment]
> Seems like this includes more changes than relevant to this particular patch?

Should be fixed now!

File: src/templates/widget-admin.php [hunk 1]
```diff
@@ -48,21 +48,56 @@
...
 			id="<?php echo $this->get_field_id('tags') ?>"
 			name="<?php echo $this->get_field_name('tags') ?>"><?php echo $instance['tags'] ?></textarea>
 </p>
+
+
+<h4>
+	<?php echo __('Fixed tag(s)', 'mailmojo') ?>
+	<small>(<?php echo __('optional', 'mailmojo') ?>)</small>
+</h4>
+<p><em><?php echo __('These tags will always be added to the subscribed contact.', 'mailmojo') ?></em></p>
```
Comment (asteinlein) [inline src/templates/widget-admin.php]: I suggest "automatically" instead of "always".
